language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
 script: chmod 755 .travis_before.sh && chmod 755 .travis_after.sh && rake mrbtest
